# acl.auth.php
# <?php exit()?>
# Don't modify the lines above
#
# Access Control Lists
#
# Auto-generated by install script
# Date: Mon, 28 Jan 2013 06:55:29 +0000
*               @ALL          0
*               @user         8
