<?php
/*
 * Dokuwiki's Main Configuration File - Local Settings
 * Auto-generated by config plugin
 * Run for user: cmcdragonkai
 * Date: Wed, 30 Jan 2013 02:16:38 +1100
 */

$conf['title'] = 'Codex @ Polycademy';
$conf['license'] = '0';
$conf['youarehere'] = 1;
$conf['useheading'] = '1';
$conf['useacl'] = 1;
$conf['passcrypt'] = 'bcrypt';
$conf['superuser'] = '@admin';
$conf['disableactions'] = 'register';
$conf['jpg_quality'] = 100;
$conf['subscribers'] = 1;
$conf['registernotify'] = 'enquiry@polycademy.com';
$conf['mailfrom'] = 'enquiry@polycademy.com';

// end auto-generated content
